ComputerWebShopSPA/Models/Data/ShoppingCart.cs
using ComputerWebShopSPA.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Models.Data
{
    public class ShoppingCart
    {
        public string ShoppingCartId { get; set; }

        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public ShoppingCart()
        {
            ShoppingCartItems = new List<ShoppingCartItem>();
        }
    }
}

ComputerWebShopSPA/Models/ViewModel/ShoppingCartViewModel.cs
using ComputerWebShopSPA.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Models.ViewModel
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }

        public ShoppingCartViewModel()
        {
            ShoppingCart = new ShoppingCart();
        }
    }
}

ComputerWebShopSPA/Controllers/OrderController.cs
using ComputerWebShopSPA.Models.Data;
using ComputerWebShopSPA.Models.Service;
using ComputerWebShopSPA.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IShoppingCartService _shoppingCartService;

        public OrderController(IOrderService orderService, IShoppingCartService shoppingCartService)
        {
            _orderService = orderService;
            _shoppingCartService = shoppingCartService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateOrder createOrder = new CreateOrder();
            return View(createOrder);
        }

        [HttpPost]
        public IActionResult Create(CreateOrder createOrder)
        {
            List<ShoppingCartItem> shoppingCartItems = _shoppingCartService.GetShoppingCartItems();

            if(shoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty");
            }

            if (ModelState.IsValid)
            {
                _orderService.Add(createOrder);
                return RedirectToAction("OrderComplete");
            }

            return View(createOrder);
        }

        public IActionResult OrderComplete()
        {
            OrderViewModel orderViewModel = new OrderViewModel();

            orderViewModel.ShoppingCartItems = _shoppingCartService.GetShoppingCartItems();
            orderViewModel.TotalCost = _shoppingCartService.CartTotalCost();

            _shoppingCartService.ClearCart();

            return View(orderViewModel);
        }
    }
}

ComputerWebShopSPA/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ComputerWebShopSPA.Models.Repo;
using ComputerWebShopSPA.Models.Service;
using ComputerWebShopSPA.Models.ViewModel;


namespace ComputerWebShopSPA.Controllers
{
    public class ShoppingCartController : Controller
    {
        //private readonly IComputerRepo _computerRepo;
        private readonly IComputerService _computerService;
        private readonly IShoppingCartService _shoppingCartService;


        public ShoppingCartController(IComputerService computerService, IShoppingCartService shoppingCartService)
        {
            _computerService = computerService;
            _shoppingCartService = shoppingCartService;
        }

        public IActionResult Index()
        {
            ShoppingCartViewModel shoppingCartViewModel = new ShoppingCartViewModel();

            shoppingCartViewModel.ShoppingCart.ShoppingCartItems = _shoppingCartService.GetShoppingCartItems(); ;
            shoppingCartViewModel.ShoppingCartTotal = _shoppingCartService.CartTotalCost();

            return View(shoppingCartViewModel);
        }

        public IActionResult AddToShoppingCart(int computerId)
        {
            var selectedComputer = _computerService.FindById(computerId);

            if(selectedComputer != null)
            {
                _shoppingCartService.AddToCart(selectedComputer, 1);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromShoppingCart(int computerId)
        {
            var selectedComputer = _computerService.FindById(computerId);

            if (selectedComputer != null)
            {
                _shoppingCartService.RemoveFromCart(selectedComputer);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ClearShoppingCart()
        {
            _shoppingCartService.ClearCart();

            return RedirectToAction("Index");
        }

    }
}

ComputerWebShopSPA/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<h2>Shopping Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="text-center">Quantity</th>
            <th class="text-center">Computer</th>
            <th class="text-center">Price</th>
            <th class="text-center">Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
        {
        <tr>
            <td class="text-center">
                <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-computerId="@item.Computer.Id" class="text-decoration-none">+ &nbsp; &nbsp; &nbsp;</a>
                @item.Amount
                <a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-computerId="@item.Computer.Id" class="text-decoration-none">&nbsp; &nbsp; &nbsp; -</a>
            </td>
            <td class="text-left">@item.Computer.Name</td>
            <td class="text-right">@item.Computer.Price.ToString("c")</td>
            <td class="text-right">
                 @((item.Amount * item.Computer.Price).ToString("c"))
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total</td>
            <td class="text-right">@Model.ShoppingCartTotal.ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div style="margin-left: 630px">
    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="ClearShoppingCart">Clear Cart</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Create">Checkout</a>
</div>