ComputerWebShopSPA/Controllers/CategoriesController.cs
using ComputerWebShopSPA.Models.Data;
using ComputerWebShopSPA.Models.Service;
using ComputerWebShopSPA.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IComputerService _computerService;

        public CategoriesController(ICategoryService categoryService, IComputerService computerService)
        {
            _categoryService = categoryService;
            _computerService = computerService;
        }

        public IActionResult Index()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel = _categoryService.All();

            return View(categoryViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateCategory createCategory = new CreateCategory();
            return View(createCategory);
        }

        [HttpPost]
        public IActionResult Create(CreateCategory createCategory)
        {
            if (ModelState.IsValid)
            {
                _categoryService.Add(createCategory);
                return RedirectToAction(nameof(Index));
            }

            return View(createCategory);
        }

        public ActionResult Edit(int id)
        {
            Category category = _categoryService.FindById(id);
            EditCategory editCategory = new EditCategory();

            if (category == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                editCategory.Id = id;
                editCategory.CreateCategory = _categoryService.CategoryToCreateCategory(category);
            }

            return View(editCategory);
        }

        [HttpPost]
        public IActionResult Edit(int id, CreateCategory createCategory)
        {
            EditCategory editCategory = new EditCategory();

            if (ModelState.IsValid)
            {
                _categoryService.Edit(id, createCategory);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                editCategory.Id = id;
                editCategory.CreateCategory = createCategory;
            }

            return View(editCategory);
        }

        [HttpGet]
        public ActionResult DeleteRequest(int id)
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Category = _categoryService.FindById(id);

            return View(categoryViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Category category = _categoryService.FindById(id);

            if (category.ComputerList.Count == 0)
            {
                _categoryService.Remove(id);
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

ComputerWebShopSPA/Controllers/ComputersController.cs
using ComputerWebShopSPA.Models.Data;
using ComputerWebShopSPA.Models.Service;
using ComputerWebShopSPA.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Controllers
{
    public class ComputersController : Controller
    {
        private readonly IComputerService _computerService;
        private readonly ICategoryService _categoryService;

        public ComputersController(IComputerService computerService, ICategoryService categoryService)
        {
            _computerService = computerService;
            _categoryService = categoryService;
        }

        public IActionResult Index(string name)
        {
            List<Computer> computerList = new List<Computer>();
            string CategoryName;

            if (string.IsNullOrEmpty(name))
            {
                computerList = _computerService.All().ComputerList.OrderBy(c => c.Name).ToList();
                CategoryName = "All Computers";
            }
            else
            {
                computerList = _computerService.All().ComputerList.Where(c => c.Category.Name == name).ToList();
                CategoryName = _categoryService.All().CategoryList.FirstOrDefault(c => c.Name == name)?.Name;
            }

            ComputerViewModel computerViewModel = new ComputerViewModel();
            computerViewModel.ComputerList = computerList;
            computerViewModel.CategoryName = CategoryName;
            
            return View(computerViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateComputer createComputer = new CreateComputer();
            createComputer.CategoryList = _categoryService.All().CategoryList;

            return View(createComputer);
        }

        [HttpPost]
        public IActionResult Create(CreateComputer createComputer)
        {
            if (ModelState.IsValid)
            {
                _computerService.Add(createComputer);
                return RedirectToAction(nameof(Index));
            }

            return View(createComputer);
        }

        public ActionResult Edit(int id)
        {
            Computer computer = _computerService.FindById(id);
            EditComputer editComputer = new EditComputer();

            if (computer == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                editComputer.Id = id;
                editComputer.CategoryList = _categoryService.All().CategoryList;
                editComputer.CreateComputer = _computerService.ComputerToCreateComputer(computer);
            }

            return View(editComputer);
        }

        [HttpPost]
        public IActionResult Edit(int id, CreateComputer createComputer)
        {
            EditComputer editComputer = new EditComputer();

            if (ModelState.IsValid)
            {
                _computerService.Edit(id, createComputer);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                editComputer.Id = id;
                editComputer.CreateComputer = createComputer;
            }

            return View(editComputer);
        }

        public IActionResult Details(int id)
        {
            Computer computer = _computerService.FindById(id);

            if (computer == null)
            {
                return RedirectToAction("Index");
            }

            ComputerViewModel computerViewModel = new ComputerViewModel();
            computerViewModel.Computer = computer;

            return View(computerViewModel);
        }

        [HttpGet]
        public ActionResult DeleteRequest(int id)
        {
            ComputerViewModel computerViewModel = new ComputerViewModel();
            computerViewModel.Computer = _computerService.FindById(id);

            return View(computerViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Computer computer = _computerService.FindById(id);
            _computerService.Remove(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ComputerWebShopSPA/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerWebShopSPA.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ComputerWebShopSPA/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ComputerWebShopSPA.Models.Repo;
using ComputerWebShopSPA.Models.Service;
using ComputerWebShopSPA.Models.ViewModel;


namespace ComputerWebShopSPA.Controllers
{
    public class ShoppingCartController : Controller
    {
        //private readonly IComputerRepo _computerRepo;
        private readonly IComputerService _computerService;
        private readonly IShoppingCartService _shoppingCartService;


        public ShoppingCartController(IComputerService computerService, IShoppingCartService shoppingCartService)
        {
            _computerService = computerService;
            _shoppingCartService = shoppingCartService;
        }

        public IActionResult Index()
        {
            ShoppingCartViewModel shoppingCartViewModel = new ShoppingCartViewModel();

            shoppingCartViewModel.ShoppingCart.ShoppingCartItems = _shoppingCartService.GetShoppingCartItems(); ;
            shoppingCartViewModel.ShoppingCartTotal = _shoppingCartService.CartTotalCost();

            return View(shoppingCartViewModel);
        }

        public IActionResult AddToShoppingCart(int computerId)
        {
            var selectedComputer = _computerService.FindById(computerId);

            if(selectedComputer != null)
            {
                _shoppingCartService.AddToCart(selectedComputer, 1);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromShoppingCart(int computerId)
        {
            var selectedComputer = _computerService.FindById(computerId);

            if (selectedComputer != null)
            {
                _shoppingCartService.RemoveFromCart(selectedComputer);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ClearShoppingCart()
        {
            _shoppingCartService.ClearCart();

            return RedirectToAction("Index");
        }

    }
}

ComputerWebShopSPA/Views/Shared/_ComputerPartialView.cshtml
@model Computer

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <a asp-controller="Computers" asp-action="Details" asp-route-id="@Model.Id">
            <img src="@Model.ImageThumbnailUrl" alt="computer image" />
        </a>
        <div class="caption">
            <h3><a asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a></h3>
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <p>@Model.Description</p>

            @if (User.IsInRole("Admin"))
            {
                <a asp-controller="Computers" asp-action="Edit" asp-route-id="@Model.Id">|Edit|</a>
                <a asp-controller="Computers" asp-action="DeleteRequest" asp-route-id="@Model.Id" style="margin-left: 10px">|Delete|</a>
            }
        </div>
        <div><p class="btn">
                 <a class="btn btn-primary" 
                    asp-controller="ShoppingCart" 
                    asp-action="AddToShoppingCart"
                    asp-route-computerId="@Model.Id">Add to Cart</a>
            </p>
        </div>
    </div>
</div>

<hr />

ComputerWebShopSPA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComputerWebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ComputerShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Computers" asp-action="Index">Computers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        <li class="nav-item">
                            @await Component.InvokeAsync("ShoppingCartSummary")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/Images/logo.png" />
                </p>
                <br />
                @await Component.InvokeAsync("CategoryMenu")
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ComputerWebShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>